# Necessary redirects -----------------------------------------------------------------------------------------

[[redirects]]
  from = "/hiring"
  to = "/booking"
  status = 301
  
[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/deep_sea_lemons/"
  status = 301
  
[[redirects]]
  from = "/facebook"
  to = "https://www.facebook.com/people/Deep-Sea-Lemons/61550058405169/"
  status = 301
  
[[redirects]]
  from = "/email"
  to = "mailto://deepsealemonsofficial@gmail.com"
  status = 301

# Custom link shortening / changing (Personal)-----------------------------------------------------------------

[[redirects]]
  from = "/link"
  to = "/"
  status = 301

[[redirects]]
  from = "/link/ruby"
  to = "https://www.instagram.com/rruby.i/"
  status = 301

[[redirects]]
  from = "/link/icons"
  to = "/404"
  status = 404

# Custom link shortening / changing (Business)-----------------------------------------------------------------

[[redirects]]
  from = "/link/aatm"
  to = "http://www.aatm.org.uk/"
  status = 301

# Custom link shortening / changing (Other)--------------------------------------------------------------------

[[redirects]]
  from = "/link/main"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  status = 301
